### ISSUE TITLE
Numpy table error, what does it mean?

### ISSUE THREAD

**Issue by areeda** [hveto/hveto#78]
While processing LHO data over all of O2 hveto crashed with the following error. I wanted to documented here because it takes about 10 hours to produce. It looks like some of the data read from CSV files came in as float32 while most of it came in as float64. I wonder if some of the omicron triggers are all zeros?

```
[hveto 1195119623]     INFO: -- Processing round 1 --
Traceback (most recent call last):
  File "/home/areeda/.local/bin/hveto", line 4, in <module>
    __import__('pkg_resources').run_script('hveto==0+untagged.263.g03337c4', 'hveto')
  File "/mnt/home6/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/home6/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/areeda/.local/lib/python2.7/site-packages/hveto-0+untagged.263.g03337c4-py2.7.egg/EGG-INFO/scripts/hveto", line 447, i
n <module>

  File "build/bdist.linux-x86_64/egg/hveto/core.py", line 166, in find_max_significance
  File "/mnt/home6/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/astropy/table/operations.py", line 190, in vstack
    out = _vstack(tables, join_type, col_name_map, metadata_conflicts)
  File "/mnt/home6/detchar/opt/gwpysoft-2.7/lib/python2.7/site-packages/astropy/table/operations.py", line 753, in _vstack
    .format(out_name, err._incompat_types))
astropy.table.np_utils.TableMergeError: The 'peak_frequency' columns have incompatible types: ['float32', 'float64', 'float64', 'float64', 'float64',...
```

**Comment by areeda** [comment]
This was my problem.  I had a stray csv file in the directory.
